# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kaja_clock.ui'
#
# Created: Mon Nov 16 23:06:01 2015
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 480)
        self.centralwidget = QtGui.QWidget(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 203, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 216, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 203, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 216, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 203, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 216, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 216, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.centralwidget.setPalette(palette)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 812, 481))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.graphics_upper = QtGui.QLabel(self.horizontalLayoutWidget)
        self.graphics_upper.setMinimumSize(QtCore.QSize(300, 0))
        self.graphics_upper.setMaximumSize(QtCore.QSize(300, 240))
        self.graphics_upper.setObjectName(_fromUtf8("graphics_upper"))
        self.verticalLayout_3.addWidget(self.graphics_upper)
        self.graphics_lower = QtGui.QLabel(self.horizontalLayoutWidget)
        self.graphics_lower.setMinimumSize(QtCore.QSize(300, 0))
        self.graphics_lower.setMaximumSize(QtCore.QSize(300, 240))
        self.graphics_lower.setObjectName(_fromUtf8("graphics_lower"))
        self.verticalLayout_3.addWidget(self.graphics_lower)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.alarm_time = QtGui.QLabel(self.horizontalLayoutWidget)
        self.alarm_time.setMinimumSize(QtCore.QSize(100, 30))
        self.alarm_time.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Simpsonfont"))
        self.alarm_time.setFont(font)
        self.alarm_time.setAlignment(QtCore.Qt.AlignCenter)
        self.alarm_time.setObjectName(_fromUtf8("alarm_time"))
        self.horizontalLayout_4.addWidget(self.alarm_time)
        self.alarm_light = QtGui.QLabel(self.horizontalLayoutWidget)
        self.alarm_light.setMinimumSize(QtCore.QSize(30, 30))
        self.alarm_light.setMaximumSize(QtCore.QSize(16777215, 35))
        self.alarm_light.setObjectName(_fromUtf8("alarm_light"))
        self.horizontalLayout_4.addWidget(self.alarm_light)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.clock = QtGui.QLabel(self.horizontalLayoutWidget)
        self.clock.setMinimumSize(QtCore.QSize(450, 0))
        self.clock.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Simpsonfont"))
        font.setPointSize(105)
        self.clock.setFont(font)
        self.clock.setObjectName(_fromUtf8("clock"))
        self.horizontalLayout_2.addWidget(self.clock)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.date = QtGui.QLabel(self.horizontalLayoutWidget)
        self.date.setMinimumSize(QtCore.QSize(480, 35))
        self.date.setMaximumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Simpsonfont"))
        self.date.setFont(font)
        self.date.setFrameShape(QtGui.QFrame.NoFrame)
        self.date.setFrameShadow(QtGui.QFrame.Sunken)
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName(_fromUtf8("date"))
        self.verticalLayout.addWidget(self.date)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(490, 40))
        self.label.setMaximumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Simpsonfont"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.yr_time_1 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.yr_time_1.setMinimumSize(QtCore.QSize(0, 36))
        self.yr_time_1.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.yr_time_1.setFont(font)
        self.yr_time_1.setText(_fromUtf8(""))
        self.yr_time_1.setObjectName(_fromUtf8("yr_time_1"))
        self.horizontalLayout_3.addWidget(self.yr_time_1)
        self.yr_time_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.yr_time_2.setMinimumSize(QtCore.QSize(0, 36))
        self.yr_time_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.yr_time_2.setFont(font)
        self.yr_time_2.setText(_fromUtf8(""))
        self.yr_time_2.setObjectName(_fromUtf8("yr_time_2"))
        self.horizontalLayout_3.addWidget(self.yr_time_2)
        self.yr_time_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.yr_time_3.setMinimumSize(QtCore.QSize(0, 36))
        self.yr_time_3.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.yr_time_3.setFont(font)
        self.yr_time_3.setText(_fromUtf8(""))
        self.yr_time_3.setObjectName(_fromUtf8("yr_time_3"))
        self.horizontalLayout_3.addWidget(self.yr_time_3)
        self.yr_time_4 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.yr_time_4.setMinimumSize(QtCore.QSize(0, 36))
        self.yr_time_4.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.yr_time_4.setFont(font)
        self.yr_time_4.setText(_fromUtf8(""))
        self.yr_time_4.setObjectName(_fromUtf8("yr_time_4"))
        self.horizontalLayout_3.addWidget(self.yr_time_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.yr_temp_1 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.yr_temp_1.setMinimumSize(QtCore.QSize(0, 36))
        self.yr_temp_1.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.yr_temp_1.setFont(font)
        self.yr_temp_1.setText(_fromUtf8(""))
        self.yr_temp_1.setObjectName(_fromUtf8("yr_temp_1"))
        self.horizontalLayout_5.addWidget(self.yr_temp_1)
        self.yr_temp_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.yr_temp_2.setMinimumSize(QtCore.QSize(0, 36))
        self.yr_temp_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.yr_temp_2.setFont(font)
        self.yr_temp_2.setText(_fromUtf8(""))
        self.yr_temp_2.setObjectName(_fromUtf8("yr_temp_2"))
        self.horizontalLayout_5.addWidget(self.yr_temp_2)
        self.yr_temp_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.yr_temp_3.setMinimumSize(QtCore.QSize(0, 36))
        self.yr_temp_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.yr_temp_3.setFont(font)
        self.yr_temp_3.setText(_fromUtf8(""))
        self.yr_temp_3.setObjectName(_fromUtf8("yr_temp_3"))
        self.horizontalLayout_5.addWidget(self.yr_temp_3)
        self.yr_temp_4 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.yr_temp_4.setMinimumSize(QtCore.QSize(0, 36))
        self.yr_temp_4.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.yr_temp_4.setFont(font)
        self.yr_temp_4.setText(_fromUtf8(""))
        self.yr_temp_4.setObjectName(_fromUtf8("yr_temp_4"))
        self.horizontalLayout_5.addWidget(self.yr_temp_4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.yr_precip_1 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.yr_precip_1.setMinimumSize(QtCore.QSize(0, 36))
        self.yr_precip_1.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.yr_precip_1.setFont(font)
        self.yr_precip_1.setText(_fromUtf8(""))
        self.yr_precip_1.setObjectName(_fromUtf8("yr_precip_1"))
        self.horizontalLayout_6.addWidget(self.yr_precip_1)
        self.yr_precip_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.yr_precip_2.setMinimumSize(QtCore.QSize(0, 36))
        self.yr_precip_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.yr_precip_2.setFont(font)
        self.yr_precip_2.setText(_fromUtf8(""))
        self.yr_precip_2.setObjectName(_fromUtf8("yr_precip_2"))
        self.horizontalLayout_6.addWidget(self.yr_precip_2)
        self.yr_precip_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.yr_precip_3.setMinimumSize(QtCore.QSize(0, 36))
        self.yr_precip_3.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.yr_precip_3.setFont(font)
        self.yr_precip_3.setText(_fromUtf8(""))
        self.yr_precip_3.setObjectName(_fromUtf8("yr_precip_3"))
        self.horizontalLayout_6.addWidget(self.yr_precip_3)
        self.yr_precip_4 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.yr_precip_4.setMinimumSize(QtCore.QSize(0, 36))
        self.yr_precip_4.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.yr_precip_4.setFont(font)
        self.yr_precip_4.setText(_fromUtf8(""))
        self.yr_precip_4.setObjectName(_fromUtf8("yr_precip_4"))
        self.horizontalLayout_6.addWidget(self.yr_precip_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.graphics_upper.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.graphics_lower.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.alarm_time.setText(QtGui.QApplication.translate("MainWindow", "No Alarm", None, QtGui.QApplication.UnicodeUTF8))
        self.alarm_light.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.clock.setText(QtGui.QApplication.translate("MainWindow", "00:00.", None, QtGui.QApplication.UnicodeUTF8))
        self.date.setText(QtGui.QApplication.translate("MainWindow", "12 Des.2015", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Good Morning Kaja!", None, QtGui.QApplication.UnicodeUTF8))

